# Generated by Django 3.2.25 on 2024-09-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('adress', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='unoauno.place')),
                ('numOfEmployees', models.IntegerField(default=1)),
            ],
        ),
    ]
