# Generated by Django 3.2.25 on 2024-09-16 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headLine', models.CharField(max_length=255)),
                ('bodyText', models.TextField()),
                ('publicDate', models.DateField(default=datetime.date.today)),
                ('rating', models.IntegerField(default=5)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.autor')),
            ],
        ),
    ]
